service: process
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /.*
  script: change_notification_client.app

libraries:
- name: numpy
  version: "1.6.1"
- name: matplotlib
  version: "1.2.0"